version: "3"
services:
  go:
    build: etc/docker/development
    container_name: go.io
    ports:
      - "80:80"
    environment:
      - URLSHORTENER_DOMAIN=go.io
      - URLSHORTENER_PORT=80
      - URLSHORTENER_LOG_DIR=/var/log/urlshortener
    volumes:
      - ./:/go/src/urlshortener
    tty: true